[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
amm = "BgnwJNWPuy4Pb19nUzEFt5uQWX2GjjEuzccArdL5kF57"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mpng/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
