[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow = "3pRcdFhMfX7xEyqpPgwmbyURiC1woZ1GjoXE3XdhDFwM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mpng/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
